import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "fr" | "en";

interface Translations {
  [key: string]: {
    fr: string;
    en: string;
  };
}

// All translations for the app
const translations: Translations = {
  // Common
  "common.home": { fr: "Accueil", en: "Home" },
  "common.search": { fr: "Rechercher", en: "Search" },
  "common.login": { fr: "Connexion", en: "Login" },
  "common.logout": { fr: "Déconnexion", en: "Logout" },
  "common.signup": { fr: "Inscription", en: "Sign up" },
  "common.profile": { fr: "Profil", en: "Profile" },
  "common.settings": { fr: "Paramètres", en: "Settings" },
  "common.dashboard": { fr: "Tableau de bord", en: "Dashboard" },
  "common.publish": { fr: "Publier", en: "Publish" },
  "common.cancel": { fr: "Annuler", en: "Cancel" },
  "common.save": { fr: "Enregistrer", en: "Save" },
  "common.delete": { fr: "Supprimer", en: "Delete" },
  "common.edit": { fr: "Modifier", en: "Edit" },
  "common.view": { fr: "Voir", en: "View" },
  "common.back": { fr: "Retour", en: "Back" },
  "common.next": { fr: "Suivant", en: "Next" },
  "common.previous": { fr: "Précédent", en: "Previous" },
  "common.loading": { fr: "Chargement...", en: "Loading..." },
  "common.error": { fr: "Erreur", en: "Error" },
  "common.success": { fr: "Succès", en: "Success" },
  "common.required": { fr: "Requis", en: "Required" },
  "common.optional": { fr: "Optionnel", en: "Optional" },
  "common.yes": { fr: "Oui", en: "Yes" },
  "common.no": { fr: "Non", en: "No" },
  "common.all": { fr: "Tous", en: "All" },
  "common.new": { fr: "Nouveau", en: "New" },
  "common.close": { fr: "Fermer", en: "Close" },
  "common.send": { fr: "Envoyer", en: "Send" },
  "common.reply": { fr: "Répondre", en: "Reply" },
  "common.assistant": { fr: "Assistant", en: "Assistant" },
  "common.messages": { fr: "Messages", en: "Messages" },
  "common.verification": { fr: "Vérification", en: "Verification" },
  "common.testimonials": { fr: "Témoignages", en: "Testimonials" },
  "common.admin": { fr: "Administration", en: "Administration" },
  "common.skip": { fr: "Passer", en: "Skip" },
  
  // Navigation
  "nav.findProperty": { fr: "Trouver un bien", en: "Find a property" },
  "nav.myListings": { fr: "Mes annonces", en: "My listings" },
  "nav.favorites": { fr: "Favoris", en: "Favorites" },
  "nav.howItWorks": { fr: "Comment ça marche", en: "How it works" },
  
  // Hero Section
  "hero.title": { fr: "Trouvez votre logement idéal au Cameroun", en: "Find your ideal home in Cameroon" },
  "hero.subtitle": { fr: "Une plateforme intelligente qui vous aide à trouver le logement parfait grâce à l'IA", en: "A smart platform that helps you find the perfect home with AI" },
  "hero.cta": { fr: "Commencer la recherche", en: "Start searching" },
  "hero.cta2": { fr: "Publier une annonce", en: "Post a listing" },
  "hero.searchPlaceholder": { fr: "Ville, quartier ou adresse...", en: "City, neighborhood or address..." },
  "hero.propertyType": { fr: "Type de bien", en: "Property type" },
  "hero.aiPowered": { fr: "Propulsé par l'Intelligence Artificielle", en: "Powered by Artificial Intelligence" },
  "hero.askAI": { fr: "Ou demandez à l'IA :", en: "Or ask the AI:" },
  "hero.activeListings": { fr: "Annonces actives", en: "Active listings" },
  "hero.citiesCovered": { fr: "Villes couvertes", en: "Cities covered" },
  "hero.satisfaction": { fr: "Satisfaction", en: "Satisfaction" },
  "hero.discover": { fr: "Découvrir", en: "Discover" },
  
  // Property Types
  "property.studio": { fr: "Studio", en: "Studio" },
  "property.apartment": { fr: "Appartement", en: "Apartment" },
  "property.house": { fr: "Maison", en: "House" },
  "property.room": { fr: "Chambre", en: "Room" },
  "property.villa": { fr: "Villa", en: "Villa" },
  
  // Listing Types
  "listing.rent": { fr: "Location", en: "Rent" },
  "listing.sale": { fr: "Vente", en: "Sale" },
  "listing.colocation": { fr: "Colocation", en: "Roommate" },
  "listing.shortTerm": { fr: "Court séjour", en: "Short stay" },
  
  // Property Details
  "property.bedroom": { fr: "chambre", en: "bedroom" },
  "property.bedrooms": { fr: "chambres", en: "bedrooms" },
  "property.bathroom": { fr: "salle de bain", en: "bathroom" },
  "property.bathrooms": { fr: "salles de bain", en: "bathrooms" },
  "property.area": { fr: "Surface", en: "Area" },
  "property.price": { fr: "Prix", en: "Price" },
  "property.deposit": { fr: "Caution", en: "Deposit" },
  "property.perMonth": { fr: "/mois", en: "/month" },
  "property.perDay": { fr: "/jour", en: "/day" },
  "property.description": { fr: "Description", en: "Description" },
  "property.amenities": { fr: "Équipements", en: "Amenities" },
  "property.rules": { fr: "Règles", en: "Rules" },
  "property.location": { fr: "Localisation", en: "Location" },
  "property.verified": { fr: "Vérifié", en: "Verified" },
  "property.available": { fr: "Disponible", en: "Available" },
  "property.unavailable": { fr: "Indisponible", en: "Unavailable" },
  "property.views": { fr: "vues", en: "views" },
  "property.owner": { fr: "Propriétaire", en: "Owner" },
  "property.reserveVisit": { fr: "Réserver une visite", en: "Book a visit" },
  "property.contactWhatsApp": { fr: "Contacter via WhatsApp", en: "Contact via WhatsApp" },
  "property.share": { fr: "Partager", en: "Share" },
  "property.favorite": { fr: "Favoris", en: "Favorite" },
  "property.report": { fr: "Signaler", en: "Report" },
  "property.minStay": { fr: "Durée minimum", en: "Minimum stay" },
  "property.days": { fr: "jours", en: "days" },
  "property.notFound": { fr: "Annonce introuvable", en: "Listing not found" },
  "property.notFoundMessage": { fr: "Cette annonce n'existe pas ou a été supprimée.", en: "This listing doesn't exist or has been deleted." },
  "property.rulesTitle": { fr: "Règles du logement", en: "House rules" },
  
  // Amenities
  "amenity.wifi": { fr: "WiFi", en: "WiFi" },
  "amenity.parking": { fr: "Parking", en: "Parking" },
  "amenity.pool": { fr: "Piscine", en: "Pool" },
  "amenity.gym": { fr: "Salle de sport", en: "Gym" },
  "amenity.security": { fr: "Sécurité 24h", en: "24h Security" },
  "amenity.generator": { fr: "Groupe électrogène", en: "Generator" },
  "amenity.waterTank": { fr: "Citerne d'eau", en: "Water tank" },
  "amenity.furnished": { fr: "Meublé", en: "Furnished" },
  "amenity.airConditioning": { fr: "Climatisation", en: "Air conditioning" },
  "amenity.garden": { fr: "Jardin", en: "Garden" },
  "amenity.balcony": { fr: "Balcon", en: "Balcony" },
  "amenity.terrace": { fr: "Terrasse", en: "Terrace" },
  "amenity.pets": { fr: "Animaux acceptés", en: "Pets allowed" },
  
  // Create Listing
  "createListing.title": { fr: "Publier une annonce", en: "Post a listing" },
  "createListing.step1": { fr: "Type", en: "Type" },
  "createListing.step2": { fr: "Localisation", en: "Location" },
  "createListing.step3": { fr: "Photos", en: "Photos" },
  "createListing.step4": { fr: "Détails", en: "Details" },
  "createListing.step5": { fr: "Aperçu", en: "Preview" },
  "createListing.propertyType": { fr: "Type de bien", en: "Property type" },
  "createListing.listingType": { fr: "Type d'annonce", en: "Listing type" },
  "createListing.whatType": { fr: "Quel type de bien souhaitez-vous publier ?", en: "What type of property do you want to list?" },
  "createListing.whereIs": { fr: "Où se trouve votre bien ?", en: "Where is your property located?" },
  "createListing.addPhotos": { fr: "Ajoutez des photos de qualité", en: "Add quality photos" },
  "createListing.photosSubtitle": { fr: "Des photos de qualité attirent plus de visiteurs", en: "Quality photos attract more visitors" },
  "createListing.titleLabel": { fr: "Titre de l'annonce", en: "Listing title" },
  "createListing.titlePlaceholder": { fr: "Ex: Bel appartement moderne à Bastos", en: "Ex: Beautiful modern apartment in Bastos" },
  "createListing.descriptionLabel": { fr: "Description", en: "Description" },
  "createListing.generateAI": { fr: "Générer avec l'IA", en: "Generate with AI" },
  "createListing.priceLabel": { fr: "Prix", en: "Price" },
  "createListing.depositLabel": { fr: "Caution", en: "Deposit" },
  "createListing.bedroomsLabel": { fr: "Chambres", en: "Bedrooms" },
  "createListing.bathroomsLabel": { fr: "Salles de bain", en: "Bathrooms" },
  "createListing.areaLabel": { fr: "Surface (m²)", en: "Area (m²)" },
  "createListing.amenitiesLabel": { fr: "Équipements", en: "Amenities" },
  "createListing.addressLabel": { fr: "Adresse / Rue", en: "Address / Street" },
  "createListing.addressRequired": { fr: "L'adresse est obligatoire", en: "Address is required" },
  "createListing.preview": { fr: "Aperçu de l'annonce", en: "Listing preview" },
  "createListing.publishBtn": { fr: "Publier l'annonce", en: "Publish listing" },
  "createListing.publishing": { fr: "Publication...", en: "Publishing..." },
  "createListing.loginRequired": { fr: "Connexion requise", en: "Login required" },
  "createListing.loginMessage": { fr: "Vous devez être connecté pour publier une annonce.", en: "You must be logged in to post a listing." },
  "createListing.success": { fr: "Annonce publiée avec succès !", en: "Listing published successfully!" },
  
  // Onboarding
  "onboarding.welcome": { fr: "Bienvenue sur Njangui", en: "Welcome to Njangui" },
  "onboarding.profileType": { fr: "Quel est votre profil ?", en: "What is your profile?" },
  "onboarding.seeker": { fr: "Je cherche un logement", en: "I'm looking for a home" },
  "onboarding.seekerDesc": { fr: "Locataire ou acheteur", en: "Tenant or buyer" },
  "onboarding.owner": { fr: "Je suis propriétaire", en: "I'm an owner" },
  "onboarding.ownerDesc": { fr: "Je mets mon bien en location/vente", en: "I'm renting/selling my property" },
  "onboarding.agent": { fr: "Je suis agent immobilier", en: "I'm a real estate agent" },
  "onboarding.agentDesc": { fr: "Je gère des biens pour des propriétaires", en: "I manage properties for owners" },
  "onboarding.agency": { fr: "Je représente une agence", en: "I represent an agency" },
  "onboarding.agencyDesc": { fr: "Agence immobilière professionnelle", en: "Professional real estate agency" },
  "onboarding.cityQuestion": { fr: "Dans quelle ville cherchez-vous ?", en: "In which city are you looking?" },
  "onboarding.cityQuestionOwner": { fr: "Dans quelle ville proposez-vous des biens ?", en: "In which city do you offer properties?" },
  "onboarding.neighborhoodsQuestion": { fr: "Quels quartiers vous intéressent ?", en: "Which neighborhoods interest you?" },
  "onboarding.neighborhoodsHint": { fr: "Séparez les quartiers par des virgules", en: "Separate neighborhoods with commas" },
  "onboarding.budgetQuestion": { fr: "Quel est votre budget mensuel ?", en: "What is your monthly budget?" },
  "onboarding.budgetMin": { fr: "Budget minimum", en: "Minimum budget" },
  "onboarding.budgetMax": { fr: "Budget maximum", en: "Maximum budget" },
  "onboarding.propertyTypeQuestion": { fr: "Quel type de bien recherchez-vous ?", en: "What type of property are you looking for?" },
  "onboarding.listingTypeQuestion": { fr: "Quel type d'offre recherchez-vous ?", en: "What type of offer are you looking for?" },
  "onboarding.moveTimelineQuestion": { fr: "Quand souhaitez-vous emménager ?", en: "When do you want to move in?" },
  "onboarding.immediate": { fr: "Immédiatement", en: "Immediately" },
  "onboarding.withinMonth": { fr: "Ce mois-ci", en: "This month" },
  "onboarding.within3Months": { fr: "D'ici 3 mois", en: "Within 3 months" },
  "onboarding.flexible": { fr: "Flexible", en: "Flexible" },
  "onboarding.amenitiesQuestion": { fr: "Quels équipements sont essentiels pour vous ?", en: "What amenities are essential for you?" },
  "onboarding.complete": { fr: "Terminer", en: "Complete" },
  
  // Dashboard
  "dashboard.title": { fr: "Tableau de bord", en: "Dashboard" },
  "dashboard.subtitle": { fr: "Gérez vos annonces et consultez les demandes", en: "Manage your listings and view inquiries" },
  "dashboard.newListing": { fr: "Nouvelle annonce", en: "New listing" },
  "dashboard.totalListings": { fr: "Annonces totales", en: "Total listings" },
  "dashboard.activeListings": { fr: "Annonces actives", en: "Active listings" },
  "dashboard.totalViews": { fr: "Vues totales", en: "Total views" },
  "dashboard.newInquiries": { fr: "Nouvelles demandes", en: "New inquiries" },
  "dashboard.myListings": { fr: "Mes annonces", en: "My listings" },
  "dashboard.inquiries": { fr: "Demandes", en: "Inquiries" },
  "dashboard.analytics": { fr: "Statistiques", en: "Analytics" },
  "dashboard.noListings": { fr: "Aucune annonce", en: "No listings" },
  "dashboard.noListingsMessage": { fr: "Publiez votre première annonce pour commencer", en: "Post your first listing to get started" },
  "dashboard.noInquiries": { fr: "Aucune demande", en: "No inquiries" },
  "dashboard.noInquiriesMessage": { fr: "Les demandes de locataires apparaîtront ici", en: "Tenant inquiries will appear here" },
  "dashboard.published": { fr: "Publié", en: "Published" },
  "dashboard.draft": { fr: "Brouillon", en: "Draft" },
  "dashboard.hide": { fr: "Masquer", en: "Hide" },
  "dashboard.show": { fr: "Publier", en: "Publish" },
  "dashboard.deleteConfirm": { fr: "Supprimer l'annonce ?", en: "Delete listing?" },
  "dashboard.deleteMessage": { fr: "Cette action est irréversible.", en: "This action cannot be undone." },
  "dashboard.for": { fr: "Pour:", en: "For:" },
  "dashboard.moveIn": { fr: "Emménagement:", en: "Move in:" },
  "dashboard.replyToInquiry": { fr: "Répondre à cette demande", en: "Reply to this inquiry" },
  
  // Booking
  "booking.title": { fr: "Réserver une visite", en: "Book a visit" },
  "booking.subtitle": { fr: "Planifiez une visite avec le propriétaire", en: "Schedule a visit with the owner" },
  "booking.selectDate": { fr: "Sélectionnez une date", en: "Select a date" },
  "booking.selectTime": { fr: "Sélectionnez une heure", en: "Select a time" },
  "booking.pickDate": { fr: "Choisir une date", en: "Pick a date" },
  "booking.pickTime": { fr: "Choisir une heure", en: "Pick a time" },
  "booking.confirm": { fr: "Confirmer la visite", en: "Confirm visit" },
  "booking.success": { fr: "Visite demandée !", en: "Visit requested!" },
  "booking.successMessage": { fr: "Le propriétaire a été notifié de votre demande de visite.", en: "The owner has been notified of your visit request." },
  "booking.errorMessage": { fr: "Impossible d'envoyer la demande de visite.", en: "Unable to send visit request." },
  "booking.loginMessage": { fr: "Connectez-vous pour réserver une visite.", en: "Login to book a visit." },
  "booking.selectDateTime": { fr: "Veuillez sélectionner une date et une heure.", en: "Please select a date and time." },
  "booking.requestTitle": { fr: "📅 Demande de visite", en: "📅 Visit request" },
  "booking.date": { fr: "Date", en: "Date" },
  "booking.time": { fr: "Heure", en: "Time" },
  "booking.defaultMessage": { fr: "Je souhaite visiter ce bien.", en: "I would like to visit this property." },
  "booking.messagePlaceholder": { fr: "Message additionnel (optionnel)...", en: "Additional message (optional)..." },
  
  // Auth
  "auth.title": { fr: "Bienvenue", en: "Welcome" },
  "auth.subtitle": { fr: "Connectez-vous ou créez un compte", en: "Sign in or create an account" },
  "auth.email": { fr: "Email", en: "Email" },
  "auth.password": { fr: "Mot de passe", en: "Password" },
  "auth.confirmPassword": { fr: "Confirmer le mot de passe", en: "Confirm password" },
  "auth.fullName": { fr: "Nom complet", en: "Full name" },
  "auth.phone": { fr: "Téléphone", en: "Phone" },
  "auth.loginBtn": { fr: "Se connecter", en: "Sign in" },
  "auth.signupBtn": { fr: "S'inscrire", en: "Sign up" },
  "auth.noAccount": { fr: "Pas de compte ?", en: "No account?" },
  "auth.hasAccount": { fr: "Déjà un compte ?", en: "Already have an account?" },
  "auth.forgotPassword": { fr: "Mot de passe oublié ?", en: "Forgot password?" },
  "auth.orContinueWith": { fr: "Ou continuer avec", en: "Or continue with" },
  
  // Profile
  "profile.title": { fr: "Mon profil", en: "My profile" },
  "profile.personalInfo": { fr: "Informations personnelles", en: "Personal information" },
  "profile.preferences": { fr: "Préférences", en: "Preferences" },
  "profile.whatsappSettings": { fr: "Paramètres WhatsApp", en: "WhatsApp settings" },
  "profile.whatsappNumber": { fr: "Numéro WhatsApp", en: "WhatsApp number" },
  "profile.whatsappHint": { fr: "Format: +237XXXXXXXXX", en: "Format: +237XXXXXXXXX" },
  "profile.enableWhatsapp": { fr: "Afficher le bouton WhatsApp sur mes annonces", en: "Show WhatsApp button on my listings" },
  "profile.bio": { fr: "Biographie", en: "Biography" },
  "profile.city": { fr: "Ville", en: "City" },
  "profile.saveChanges": { fr: "Enregistrer les modifications", en: "Save changes" },
  "profile.saving": { fr: "Enregistrement...", en: "Saving..." },
  "profile.backToHome": { fr: "Retour à l'accueil", en: "Back to home" },
  "profile.yourProfile": { fr: "Votre profil", en: "Your profile" },
  "profile.notVerified": { fr: "Non vérifié", en: "Not verified" },
  "profile.verificationCTA": { fr: "Vérification & Trust Score", en: "Verification & Trust Score" },
  "profile.increaseCredibility": { fr: "Augmentez votre crédibilité", en: "Increase your credibility" },
  "profile.points": { fr: "points", en: "points" },
  "profile.iAm": { fr: "Je suis", en: "I am" },
  "profile.seeker": { fr: "Chercheur", en: "Seeker" },
  "profile.ownerLabel": { fr: "Propriétaire", en: "Owner" },
  "profile.both": { fr: "Les deux", en: "Both" },
  "profile.fullName": { fr: "Nom complet", en: "Full name" },
  "profile.phone": { fr: "Téléphone", en: "Phone" },
  "profile.aboutMe": { fr: "À propos de moi", en: "About me" },
  "profile.aboutMePlaceholder": { fr: "Parlez de vous...", en: "Tell us about yourself..." },
  "profile.monthlyBudget": { fr: "Budget mensuel (FCFA)", en: "Monthly budget (FCFA)" },
  "profile.budgetMin": { fr: "Minimum", en: "Minimum" },
  "profile.budgetMax": { fr: "Maximum", en: "Maximum" },
  "profile.moveInWhen": { fr: "Quand souhaitez-vous emménager ?", en: "When do you want to move in?" },
  "profile.immediate": { fr: "Immédiatement", en: "Immediately" },
  "profile.withinMonth": { fr: "Ce mois-ci", en: "This month" },
  "profile.within3Months": { fr: "D'ici 3 mois", en: "Within 3 months" },
  "profile.flexible": { fr: "Flexible", en: "Flexible" },
  "profile.preferredNeighborhoods": { fr: "Quartiers préférés", en: "Preferred neighborhoods" },
  "profile.neighborhoodsPlaceholder": { fr: "Bastos, Mvan, Essos... (séparés par des virgules)", en: "Bastos, Mvan, Essos... (comma separated)" },
  "profile.propertyTypesWanted": { fr: "Types de bien recherchés", en: "Property types wanted" },
  "profile.listingTypesWanted": { fr: "Types d'offres recherchées", en: "Offer types wanted" },
  "profile.essentialAmenities": { fr: "Équipements essentiels", en: "Essential amenities" },
  "profile.ownerSettings": { fr: "Paramètres propriétaire", en: "Owner settings" },
  "profile.whatsappExplanation": { fr: "Ce numéro sera utilisé pour le bouton WhatsApp sur vos annonces", en: "This number will be used for the WhatsApp button on your listings" },
  "profile.tip": { fr: "Conseil", en: "Tip" },
  "profile.tipText": { fr: "Ajoutez votre numéro WhatsApp pour permettre aux chercheurs de vous contacter directement depuis vos annonces. Vous pourrez activer/désactiver cette option pour chaque annonce individuellement.", en: "Add your WhatsApp number to allow seekers to contact you directly from your listings. You can enable/disable this option for each listing individually." },
  "profile.loadError": { fr: "Impossible de charger votre profil.", en: "Unable to load your profile." },
  "profile.uploadError": { fr: "Impossible d'uploader l'image.", en: "Unable to upload image." },
  "profile.avatarUpdated": { fr: "Photo de profil mise à jour !", en: "Profile picture updated!" },
  "profile.avatarSelected": { fr: "Avatar sélectionné !", en: "Avatar selected!" },
  "profile.selectError": { fr: "Impossible de sélectionner l'avatar.", en: "Unable to select avatar." },
  "profile.updated": { fr: "Profil mis à jour !", en: "Profile updated!" },
  "profile.updatedDesc": { fr: "Vos modifications ont été enregistrées.", en: "Your changes have been saved." },
  "profile.saveError": { fr: "Impossible de sauvegarder.", en: "Unable to save." },
  "profile.choosePhoto": { fr: "Choisir une photo de profil", en: "Choose a profile picture" },
  "profile.uploadImage": { fr: "Uploader une image", en: "Upload an image" },
  "profile.chooseImage": { fr: "Choisir une image", en: "Choose an image" },
  "profile.orChooseAvatar": { fr: "Ou choisir un avatar", en: "Or choose an avatar" },
  
  // Verification
  "verification.title": { fr: "Vérification de compte", en: "Account verification" },
  "verification.level1": { fr: "Niveau 1 - Basique", en: "Level 1 - Basic" },
  "verification.level2": { fr: "Niveau 2 - Standard", en: "Level 2 - Standard" },
  "verification.level3": { fr: "Niveau 3 - Avancé", en: "Level 3 - Advanced" },
  "verification.level4": { fr: "Niveau 4 - Premium", en: "Level 4 - Premium" },
  "verification.emailVerified": { fr: "Email vérifié", en: "Email verified" },
  "verification.phoneVerified": { fr: "Téléphone vérifié", en: "Phone verified" },
  "verification.idVerified": { fr: "Identité vérifiée", en: "Identity verified" },
  "verification.sendOtp": { fr: "Envoyer le code", en: "Send code" },
  "verification.verifyOtp": { fr: "Vérifier le code", en: "Verify code" },
  "verification.enterOtp": { fr: "Entrez le code reçu", en: "Enter the received code" },
  
  // Admin Dashboard
  "admin.title": { fr: "Tableau de bord administrateur", en: "Admin Dashboard" },
  "admin.subtitle": { fr: "Gérez les vérifications et les signalements", en: "Manage verifications and reports" },
  "admin.analytics": { fr: "Statistiques", en: "Analytics" },
  "admin.documents": { fr: "Documents", en: "Documents" },
  "admin.reports": { fr: "Signalements", en: "Reports" },
  "admin.users": { fr: "Utilisateurs", en: "Users" },
  "admin.properties": { fr: "Propriétés", en: "Properties" },
  "admin.viewsToday": { fr: "Vues aujourd'hui", en: "Views today" },
  "admin.pendingDocs": { fr: "Documents en attente", en: "Pending documents" },
  "admin.pendingReports": { fr: "Signalements en attente", en: "Pending reports" },
  "admin.approve": { fr: "Approuver", en: "Approve" },
  "admin.reject": { fr: "Rejeter", en: "Reject" },
  "admin.validate": { fr: "Valider", en: "Validate" },
  "admin.pending": { fr: "En attente", en: "Pending" },
  "admin.approved": { fr: "Approuvé", en: "Approved" },
  "admin.rejected": { fr: "Rejeté", en: "Rejected" },
  "admin.reviewDocument": { fr: "Examiner le document", en: "Review document" },
  "admin.reviewReport": { fr: "Examiner le signalement", en: "Review report" },
  "admin.rejectionReason": { fr: "Raison du rejet", en: "Rejection reason" },
  "admin.resolutionNotes": { fr: "Notes de résolution", en: "Resolution notes" },
  "admin.views7days": { fr: "Vues (7 jours)", en: "Views (7 days)" },
  "admin.totalConversations": { fr: "Conversations", en: "Conversations" },
  "admin.totalInquiries": { fr: "Demandes", en: "Inquiries" },
  "admin.verifiedUsers": { fr: "Utilisateurs vérifiés", en: "Verified users" },
  "admin.newUsersWeek": { fr: "Nouveaux cette semaine", en: "New this week" },
  "admin.newPropertiesWeek": { fr: "Nouvelles annonces", en: "New listings" },
  "admin.propertyDistribution": { fr: "Répartition par type de bien", en: "Distribution by property type" },
  "admin.listingDistribution": { fr: "Répartition par type d'offre", en: "Distribution by listing type" },
  "admin.trafficEvolution": { fr: "Évolution du trafic", en: "Traffic evolution" },
  "admin.globalStats": { fr: "Vue d'ensemble", en: "Overview" },
  "admin.performanceIndicators": { fr: "Indicateurs de performance", en: "Performance indicators" },
  "admin.conversionRate": { fr: "Taux de conversion", en: "Conversion rate" },
  "admin.avgViewsPerProperty": { fr: "Vues moy. par annonce", en: "Avg views per listing" },
  "admin.activeUsers": { fr: "Utilisateurs actifs", en: "Active users" },
  "admin.documentsCount": { fr: "Total documents", en: "Total documents" },
  "admin.accessDenied": { fr: "Accès refusé", en: "Access denied" },
  "admin.noAdminRights": { fr: "Vous n'avez pas les droits administrateur", en: "You don't have admin rights" },
  "admin.loadError": { fr: "Impossible de charger les données", en: "Unable to load data" },
  "admin.documentApproved": { fr: "Document approuvé", en: "Document approved" },
  "admin.documentRejected": { fr: "Document rejeté", en: "Document rejected" },
  "admin.reportProcessed": { fr: "Signalement traité", en: "Report processed" },
  "admin.noDocsToShow": { fr: "Aucun document à afficher", en: "No documents to display" },
  "admin.noReportsToShow": { fr: "Aucun signalement à afficher", en: "No reports to display" },
  "admin.verificationDocs": { fr: "Documents de vérification", en: "Verification documents" },
  "admin.userReports": { fr: "Signalements utilisateurs", en: "User reports" },
  "admin.noDescription": { fr: "Pas de description", en: "No description" },
  "admin.processed": { fr: "Traité", en: "Processed" },
  "admin.user": { fr: "Utilisateur", en: "User" },
  "admin.date": { fr: "Date", en: "Date" },
  "admin.type": { fr: "Type", en: "Type" },
  "admin.property": { fr: "Annonce", en: "Listing" },
  "admin.rejectionReasonRequired": { fr: "Veuillez indiquer la raison du rejet", en: "Please provide rejection reason" },
  "admin.validateReport": { fr: "Valider le signalement", en: "Validate report" },
  "admin.reportValidated": { fr: "Signalement validé", en: "Report validated" },
  "admin.reportRejected": { fr: "Signalement rejeté", en: "Report rejected" },
  "admin.all": { fr: "Tous", en: "All" },
  "admin.back": { fr: "Retour", en: "Back" },
  "admin.publishedProperties": { fr: "Annonces publiées", en: "Published listings" },
  "admin.seekers": { fr: "Chercheurs", en: "Seekers" },
  "admin.owners": { fr: "Propriétaires", en: "Owners" },
  "admin.agents": { fr: "Agents", en: "Agents" },
  
  // Search
  "search.title": { fr: "Rechercher un bien", en: "Search for property" },
  "search.placeholder": { fr: "Où cherchez-vous ?", en: "Where are you looking?" },
  "search.filters": { fr: "Filtres", en: "Filters" },
  "search.priceRange": { fr: "Fourchette de prix", en: "Price range" },
  "search.propertyType": { fr: "Type de bien", en: "Property type" },
  "search.bedrooms": { fr: "Chambres", en: "Bedrooms" },
  "search.results": { fr: "résultats", en: "results" },
  "search.noResults": { fr: "Aucun résultat", en: "No results" },
  "search.noResultsMessage": { fr: "Essayez d'ajuster vos filtres", en: "Try adjusting your filters" },
  "search.sortBy": { fr: "Trier par", en: "Sort by" },
  "search.newest": { fr: "Plus récent", en: "Newest" },
  "search.priceLowHigh": { fr: "Prix croissant", en: "Price: Low to High" },
  "search.priceHighLow": { fr: "Prix décroissant", en: "Price: High to Low" },

  // Filters
  "filter.listingType": { fr: "Type d'annonce", en: "Listing type" },
  "filter.city": { fr: "Ville", en: "City" },
  "filter.chooseCity": { fr: "Choisir une ville", en: "Choose a city" },
  "filter.neighborhood": { fr: "Quartier", en: "Neighborhood" },
  "filter.neighborhoodPlaceholder": { fr: "Ex: Bastos, Bonanjo...", en: "Ex: Bastos, Bonanjo..." },
  "filter.budget": { fr: "Budget (FCFA)", en: "Budget (FCFA)" },
  "filter.min": { fr: "Min", en: "Min" },
  "filter.max": { fr: "Max", en: "Max" },
  "filter.bathrooms": { fr: "SDB", en: "Bath" },
  "filter.all": { fr: "Toutes", en: "All" },
  "filter.amenities": { fr: "Commodités", en: "Amenities" },
  "filter.clear": { fr: "Effacer", en: "Clear" },
  "filter.apply": { fr: "Appliquer", en: "Apply" },
  "filter.wifi": { fr: "Wi-Fi", en: "Wi-Fi" },
  "filter.airConditioning": { fr: "Climatisation", en: "Air conditioning" },
  "filter.parking": { fr: "Parking", en: "Parking" },
  "filter.security": { fr: "Gardien", en: "Security" },
  "filter.pool": { fr: "Piscine", en: "Pool" },
  "filter.gym": { fr: "Sport", en: "Gym" },
  "filter.garden": { fr: "Jardin", en: "Garden" },
  "filter.generator": { fr: "Groupe", en: "Generator" },

  // Testimonials
  "testimonials.badge": { fr: "Témoignages", en: "Testimonials" },
  "testimonials.title": { fr: "Ce que nos utilisateurs disent", en: "What our users say" },
  "testimonials.subtitle": { fr: "Des milliers de personnes ont trouvé leur logement idéal grâce à Njangui", en: "Thousands of people found their ideal home thanks to Njangui" },
  "testimonials.viewAll": { fr: "Voir tous les témoignages", en: "View all testimonials" },
  "testimonials.user": { fr: "Utilisateur", en: "User" },
  "testimonials.userAt": { fr: "Utilisateur à", en: "User at" },
  "testimonials.userNjangui": { fr: "Utilisateur Njangui", en: "Njangui User" },

  // Property Card
  "card.verified": { fr: "Vérifié", en: "Verified" },
  "card.reviews": { fr: "avis", en: "reviews" },
  "card.viewDetails": { fr: "Voir détails", en: "View details" },
  
  // Messages
  "messages.title": { fr: "Messages", en: "Messages" },
  "messages.noConversations": { fr: "Aucune conversation", en: "No conversations" },
  "messages.startConversation": { fr: "Démarrer une conversation", en: "Start a conversation" },
  "messages.typePlaceholder": { fr: "Tapez votre message...", en: "Type your message..." },
  
  // Contact Form
  "contact.name": { fr: "Votre nom", en: "Your name" },
  "contact.email": { fr: "Votre email", en: "Your email" },
  "contact.phone": { fr: "Votre téléphone", en: "Your phone" },
  "contact.message": { fr: "Votre message", en: "Your message" },
  "contact.moveInDate": { fr: "Date d'emménagement souhaitée", en: "Desired move-in date" },
  "contact.sendInquiry": { fr: "Envoyer la demande", en: "Send inquiry" },
  "contact.sending": { fr: "Envoi...", en: "Sending..." },
  "contact.success": { fr: "Demande envoyée avec succès !", en: "Inquiry sent successfully!" },
  
  // How It Works
  "hiw.title": { fr: "Comment ça marche", en: "How it works" },
  "hiw.subtitle": { fr: "Trouvez votre prochain logement en quelques étapes simples", en: "Find your next home in a few simple steps" },
  "hiw.step1Title": { fr: "Recherchez", en: "Search" },
  "hiw.step1Desc": { fr: "Utilisez notre IA pour décrire votre logement idéal ou parcourez les annonces.", en: "Use our AI to describe your ideal home or browse listings." },
  "hiw.step2Title": { fr: "Contactez", en: "Contact" },
  "hiw.step2Desc": { fr: "Échangez directement avec les propriétaires via notre messagerie sécurisée.", en: "Chat directly with owners via our secure messaging." },
  "hiw.step3Title": { fr: "Réservez", en: "Book" },
  "hiw.step3Desc": { fr: "Planifiez une visite ou réservez directement si le logement vous convient.", en: "Schedule a visit or book directly if the property suits you." },
  "hiw.step4Title": { fr: "Emménagez", en: "Move in" },
  "hiw.step4Desc": { fr: "Finalisez la transaction en toute sécurité et recevez vos clés.", en: "Finalize the transaction securely and receive your keys." },
  
  // CTA Section
  "cta.seekerTitle": { fr: "Vous cherchez un logement ?", en: "Looking for a home?" },
  "cta.seekerDesc": { fr: "Accédez à des milliers d'annonces vérifiées et trouvez votre prochain chez-vous grâce à notre IA.", en: "Access thousands of verified listings and find your next home with our AI." },
  "cta.seekerBtn": { fr: "Commencer la recherche", en: "Start searching" },
  "cta.ownerTitle": { fr: "Vous êtes propriétaire ?", en: "Are you an owner?" },
  "cta.ownerDesc": { fr: "Publiez votre annonce gratuitement et trouvez des locataires fiables en quelques clics.", en: "Post your listing for free and find reliable tenants in a few clicks." },
  "cta.ownerBtn": { fr: "Publier une annonce", en: "Post a listing" },
  
  // Trust Section
  "trust.title": { fr: "Une plateforme de confiance pour votre recherche", en: "A trusted platform for your search" },
  "trust.subtitle": { fr: "Nous mettons tout en œuvre pour protéger locataires et propriétaires. Chaque annonce est vérifiée et chaque transaction est sécurisée.", en: "We do everything to protect tenants and owners. Every listing is verified and every transaction is secure." },
  "trust.badge": { fr: "Sécurité & Confiance", en: "Security & Trust" },
  "trust.activeUsers": { fr: "Utilisateurs actifs", en: "Active users" },
  "trust.secureTransactions": { fr: "Transactions sécurisées", en: "Secure transactions" },
  "trust.averageRating": { fr: "Note moyenne", en: "Average rating" },
  "trust.verifiedOwners": { fr: "Propriétaires vérifiés", en: "Verified owners" },
  "trust.feature1": { fr: "Vérification d'identité obligatoire", en: "Mandatory identity verification" },
  "trust.feature2": { fr: "Paiements sécurisés", en: "Secure payments" },
  "trust.feature3": { fr: "Support client 24/7", en: "24/7 customer support" },
  "trust.feature4": { fr: "Annonces modérées par l'IA", en: "AI-moderated listings" },
  "trust.feature5": { fr: "Protection anti-fraude", en: "Anti-fraud protection" },
  "trust.feature6": { fr: "Garantie satisfaction", en: "Satisfaction guarantee" },
  
  // Featured Properties
  "featured.title": { fr: "Annonces en vedette", en: "Featured listings" },
  "featured.subtitle": { fr: "Découvrez les logements les mieux notés sélectionnés par notre IA", en: "Discover top-rated properties selected by our AI" },
  "featured.recommended": { fr: "Recommandé pour vous", en: "Recommended for you" },
  "featured.all": { fr: "Tous", en: "All" },
  "featured.loading": { fr: "Chargement des recommandations...", en: "Loading recommendations..." },
  "featured.viewMore": { fr: "Voir plus d'annonces", en: "View more listings" },
  "featured.noResults": { fr: "Aucune propriété trouvée pour ce filtre", en: "No property found for this filter" },
  
  // Footer
  "footer.about": { fr: "À propos", en: "About" },
  "footer.contact": { fr: "Contact", en: "Contact" },
  "footer.privacy": { fr: "Confidentialité", en: "Privacy" },
  "footer.terms": { fr: "Conditions", en: "Terms" },
  "footer.faq": { fr: "FAQ", en: "FAQ" },
  "footer.copyright": { fr: "Tous droits réservés", en: "All rights reserved" },
  "footer.platform": { fr: "Plateforme", en: "Platform" },
  "footer.resources": { fr: "Ressources", en: "Resources" },
  "footer.company": { fr: "Entreprise", en: "Company" },
  "footer.legal": { fr: "Légal", en: "Legal" },
  "footer.howItWorks": { fr: "Comment ça marche", en: "How it works" },
  "footer.pricing": { fr: "Tarifs", en: "Pricing" },
  "footer.helpCenter": { fr: "Centre d'aide", en: "Help center" },
  "footer.blog": { fr: "Blog", en: "Blog" },
  "footer.tenantGuide": { fr: "Guide du locataire", en: "Tenant guide" },
  "footer.ownerGuide": { fr: "Guide du propriétaire", en: "Owner guide" },
  "footer.careers": { fr: "Carrières", en: "Careers" },
  "footer.press": { fr: "Presse", en: "Press" },
  "footer.termsOfUse": { fr: "Conditions d'utilisation", en: "Terms of use" },
  "footer.privacyPolicy": { fr: "Politique de confidentialité", en: "Privacy policy" },
  "footer.cookies": { fr: "Cookies", en: "Cookies" },
  "footer.description": { fr: "La plateforme immobilière intelligente qui révolutionne la recherche de logement en Afrique.", en: "The smart real estate platform revolutionizing home search in Africa." },
  
  // Testimonials Page
  "testimonialsPage.title": { fr: "Témoignages", en: "Testimonials" },
  "testimonialsPage.metaTitle": { fr: "Témoignages | Njangui - Avis de nos utilisateurs", en: "Testimonials | Njangui - User Reviews" },
  "testimonialsPage.metaDesc": { fr: "Découvrez les témoignages de nos utilisateurs. Partagez votre expérience avec Njangui.", en: "Discover testimonials from our users. Share your experience with Njangui." },
  "testimonialsPage.headerTitle": { fr: "Ce que disent nos utilisateurs", en: "What our users say" },
  "testimonialsPage.headerSubtitle": { fr: "Partagez votre expérience et découvrez les avis de notre communauté", en: "Share your experience and discover reviews from our community" },
  "testimonialsPage.shareExperience": { fr: "Partagez votre expérience", en: "Share your experience" },
  "testimonialsPage.yourRating": { fr: "Votre note", en: "Your rating" },
  "testimonialsPage.yourTestimonial": { fr: "Votre témoignage", en: "Your testimonial" },
  "testimonialsPage.placeholder": { fr: "Partagez votre expérience avec Njangui...", en: "Share your experience with Njangui..." },
  "testimonialsPage.submit": { fr: "Envoyer", en: "Submit" },
  "testimonialsPage.submitting": { fr: "Envoi...", en: "Submitting..." },
  "testimonialsPage.approvalNotice": { fr: "Votre témoignage sera visible après approbation", en: "Your testimonial will be visible after approval" },
  "testimonialsPage.loginToShare": { fr: "Connectez-vous pour partager votre expérience", en: "Log in to share your experience" },
  "testimonialsPage.myTestimonials": { fr: "Mes témoignages", en: "My testimonials" },
  "testimonialsPage.approved": { fr: "Approuvé", en: "Approved" },
  "testimonialsPage.pending": { fr: "En attente", en: "Pending" },
  "testimonialsPage.noTestimonials": { fr: "Aucun témoignage pour le moment. Soyez le premier à partager votre expérience !", en: "No testimonials yet. Be the first to share your experience!" },
  "testimonialsPage.userAt": { fr: "Utilisateur à", en: "User at" },
  "testimonialsPage.NjanguiUser": { fr: "Utilisateur Njangui", en: "Njangui User" },
  "testimonialsPage.loginRequired": { fr: "Vous devez être connecté pour laisser un témoignage", en: "You must be logged in to leave a testimonial" },
  "testimonialsPage.writeTestimonial": { fr: "Veuillez écrire votre témoignage", en: "Please write your testimonial" },
  "testimonialsPage.success": { fr: "Témoignage envoyé ! Il sera visible après approbation.", en: "Testimonial submitted! It will be visible after approval." },
  "testimonialsPage.error": { fr: "Erreur lors de l'envoi du témoignage", en: "Error submitting testimonial" },
  "testimonialsPage.likeError": { fr: "Erreur lors du like", en: "Error liking" },
  "testimonialsPage.loginToLike": { fr: "Vous devez être connecté pour liker", en: "You must be logged in to like" },
  
  // Assistant Page
  "assistant.title": { fr: "Assistant IA Immobilier | Njangui", en: "Real Estate AI Assistant | Njangui" },
  "assistant.metaDesc": { fr: "Trouvez votre logement idéal avec notre assistant IA. Décrivez vos critères en langage naturel et recevez des recommandations personnalisées.", en: "Find your ideal home with our AI assistant. Describe your criteria in natural language and receive personalized recommendations." },
  "assistant.newConversation": { fr: "Nouvelle conversation", en: "New conversation" },
  "assistant.noConversations": { fr: "Aucune conversation", en: "No conversations" },
  "assistant.backHome": { fr: "Retour à l'accueil", en: "Back to home" },
  "assistant.realEstateAssistant": { fr: "Assistant Immobilier", en: "Real Estate Assistant" },
  "assistant.login": { fr: "Connexion", en: "Login" },
  "assistant.howCanIHelp": { fr: "Comment puis-je vous aider ?", en: "How can I help you?" },
  "assistant.describeHome": { fr: "Décrivez le logement de vos rêves et je vous propose les meilleures options au Cameroun.", en: "Describe your dream home and I'll suggest the best options in Cameroon." },
  "assistant.loginPrompt": { fr: "pour accéder à l'assistant IA et sauvegarder vos conversations.", en: "to access the AI assistant and save your conversations." },
  "assistant.you": { fr: "Vous", en: "You" },
  "assistant.assistantName": { fr: "Njangui", en: "Njangui" },
  "assistant.propertiesFound": { fr: "propriété(s) trouvée(s)", en: "property(ies) found" },
  "assistant.copied": { fr: "Copié dans le presse-papiers", en: "Copied to clipboard" },
  "assistant.thinking": { fr: "Recherche en cours...", en: "Searching..." },
  "assistant.inputPlaceholder": { fr: "Décrivez le logement que vous recherchez...", en: "Describe the home you're looking for..." },
  "assistant.inputPlaceholderDisabled": { fr: "Connectez-vous pour utiliser l'assistant", en: "Log in to use the assistant" },
  "assistant.disclaimer": { fr: "L'assistant peut faire des erreurs. Vérifiez les informations importantes.", en: "The assistant may make mistakes. Verify important information." },
  "assistant.suggestion1Title": { fr: "Studio meublé", en: "Furnished studio" },
  "assistant.suggestion1Prompt": { fr: "Je cherche un studio meublé à Yaoundé moins de 100 000 FCFA par mois", en: "I'm looking for a furnished studio in Yaoundé under 100,000 FCFA per month" },
  "assistant.suggestion2Title": { fr: "Appartement familial", en: "Family apartment" },
  "assistant.suggestion2Prompt": { fr: "Un appartement 3 chambres à Douala avec parking et sécurité", en: "A 3-bedroom apartment in Douala with parking and security" },
  "assistant.suggestion3Title": { fr: "Colocation étudiante", en: "Student shared housing" },
  "assistant.suggestion3Prompt": { fr: "Une colocation proche de l'université de Ngoa-Ekelle pour étudiant", en: "Shared housing near Ngoa-Ekelle University for student" },
  "assistant.suggestion4Title": { fr: "Villa de luxe", en: "Luxury villa" },
  "assistant.suggestion4Prompt": { fr: "Villa avec piscine et jardin à Bastos pour une famille", en: "Villa with pool and garden in Bastos for a family" },
  
  // Seeker Dashboard
  "seekerDashboard.title": { fr: "Mon espace | Njangui", en: "My space | Njangui" },
  "seekerDashboard.metaDesc": { fr: "Gérez vos recherches et favoris immobiliers", en: "Manage your property searches and favorites" },
  "seekerDashboard.hello": { fr: "Bonjour", en: "Hello" },
  "seekerDashboard.findSearches": { fr: "Retrouvez vos recherches et favoris", en: "Find your searches and favorites" },
  "seekerDashboard.search": { fr: "Rechercher", en: "Search" },
  "seekerDashboard.exploreListings": { fr: "Explorer les annonces", en: "Explore listings" },
  "seekerDashboard.aiAssistant": { fr: "Assistant IA", en: "AI Assistant" },
  "seekerDashboard.personalizedHelp": { fr: "Aide personnalisée", en: "Personalized help" },
  "seekerDashboard.messages": { fr: "Messages", en: "Messages" },
  "seekerDashboard.yourConversations": { fr: "Vos conversations", en: "Your conversations" },
  "seekerDashboard.searchPreferences": { fr: "Vos préférences de recherche", en: "Your search preferences" },
  "seekerDashboard.modifyPreferences": { fr: "Modifier mes préférences", en: "Modify my preferences" },
  "seekerDashboard.myFavorites": { fr: "Mes favoris", en: "My favorites" },
  "seekerDashboard.noFavorites": { fr: "Aucun favori", en: "No favorites" },
  "seekerDashboard.saveFavorites": { fr: "Sauvegardez des annonces pour les retrouver ici", en: "Save listings to find them here" },
  "seekerDashboard.browseListings": { fr: "Parcourir les annonces", en: "Browse listings" },
  "seekerDashboard.removedFromFavorites": { fr: "Retiré des favoris", en: "Removed from favorites" },
  "seekerDashboard.error": { fr: "Erreur", en: "Error" },
  "seekerDashboard.loadError": { fr: "Impossible de charger les données", en: "Unable to load data" },
  "seekerDashboard.removeError": { fr: "Impossible de retirer des favoris", en: "Unable to remove from favorites" },
  "seekerDashboard.rooms": { fr: "ch", en: "bd" },
  "seekerDashboard.bathrooms": { fr: "sdb", en: "ba" },
  
  // Property Amenities
  "amenities.title": { fr: "Équipements & commodités", en: "Amenities & features" },
  "amenities.wifi": { fr: "Wi-Fi", en: "Wi-Fi" },
  "amenities.parking": { fr: "Parking", en: "Parking" },
  "amenities.security": { fr: "Sécurité 24h", en: "24h Security" },
  "amenities.water": { fr: "Eau courante", en: "Running water" },
  "amenities.electricity": { fr: "Électricité", en: "Electricity" },
  "amenities.ac": { fr: "Climatisation", en: "Air conditioning" },
  "amenities.tv": { fr: "Télévision", en: "Television" },
  "amenities.kitchen": { fr: "Cuisine équipée", en: "Equipped kitchen" },
  "amenities.laundry": { fr: "Machine à laver", en: "Washing machine" },
  "amenities.gym": { fr: "Salle de sport", en: "Gym" },
  "amenities.garden": { fr: "Jardin", en: "Garden" },
  "amenities.pool": { fr: "Piscine", en: "Pool" },
  "amenities.pets": { fr: "Animaux acceptés", en: "Pets allowed" },
  "amenities.smoking": { fr: "Fumeurs acceptés", en: "Smoking allowed" },
  "amenities.family": { fr: "Idéal familles", en: "Family friendly" },
  "amenities.baby": { fr: "Équipement bébé", en: "Baby equipment" },
  "amenities.accessible": { fr: "Accessible PMR", en: "Wheelchair accessible" },
  "amenities.cleaning": { fr: "Ménage inclus", en: "Cleaning included" },
  
  // WhatsApp Button
  "whatsapp.contact": { fr: "Contacter via WhatsApp", en: "Contact via WhatsApp" },
  "whatsapp.message": { fr: "Bonjour ! Je suis intéressé(e) par votre annonce \"{title}\" sur Njangui. Est-elle toujours disponible ?", en: "Hello! I'm interested in your listing \"{title}\" on Njangui. Is it still available?" },
  
  // Property Preview
  "preview.title": { fr: "Aperçu de l'annonce", en: "Listing preview" },
  "preview.checkInfo": { fr: "Vérifiez les informations avant publication", en: "Check the information before publishing" },
  "preview.mainPhoto": { fr: "Photo principale", en: "Main photo" },
  "preview.noTitle": { fr: "Sans titre", en: "No title" },
  "preview.locationNotSpecified": { fr: "Localisation non spécifiée", en: "Location not specified" },
  "preview.perMonth": { fr: "mois", en: "month" },
  "preview.perDay": { fr: "jour", en: "day" },
  "preview.sale": { fr: "vente", en: "sale" },
  "preview.deposit": { fr: "Caution", en: "Deposit" },
  "preview.bedrooms": { fr: "chambre(s)", en: "bedroom(s)" },
  "preview.bathrooms": { fr: "salle(s) de bain", en: "bathroom(s)" },
  "preview.description": { fr: "Description", en: "Description" },
  "preview.amenities": { fr: "Commodités", en: "Amenities" },
  "preview.address": { fr: "Adresse", en: "Address" },
  "preview.modify": { fr: "Modifier", en: "Modify" },
  "preview.publish": { fr: "Publier l'annonce", en: "Publish listing" },
  "preview.publishing": { fr: "Publication...", en: "Publishing..." },
  "preview.studio": { fr: "Studio", en: "Studio" },
  "preview.apartment": { fr: "Appartement", en: "Apartment" },
  "preview.house": { fr: "Maison", en: "House" },
  "preview.room": { fr: "Chambre", en: "Room" },
  "preview.villa": { fr: "Villa", en: "Villa" },
  "preview.rent": { fr: "Location", en: "Rent" },
  "preview.saleListing": { fr: "Vente", en: "Sale" },
  "preview.colocation": { fr: "Colocation", en: "Roommate" },
  "preview.shortTerm": { fr: "Court séjour", en: "Short stay" },
  "preview.amenityWifi": { fr: "WiFi", en: "WiFi" },
  "preview.amenityParking": { fr: "Parking", en: "Parking" },
  "preview.amenityPool": { fr: "Piscine", en: "Pool" },
  "preview.amenityGym": { fr: "Salle de sport", en: "Gym" },
  "preview.amenitySecurity": { fr: "Sécurité 24h", en: "24h Security" },
  "preview.amenityGenerator": { fr: "Groupe électrogène", en: "Generator" },
  "preview.amenityWaterTank": { fr: "Citerne d'eau", en: "Water tank" },
  "preview.amenityFurnished": { fr: "Meublé", en: "Furnished" },
  "preview.amenityAC": { fr: "Climatisation", en: "Air conditioning" },
  "preview.amenityGarden": { fr: "Jardin", en: "Garden" },
  "preview.amenityBalcony": { fr: "Balcon", en: "Balcony" },
  "preview.amenityTerrace": { fr: "Terrasse", en: "Terrace" },
  
  // Notification Preferences
  "notif.title": { fr: "Préférences de notifications", en: "Notification Preferences" },
  "notif.description": { fr: "Gérez comment et quand vous recevez des notifications", en: "Manage how and when you receive notifications" },
  "notif.email": { fr: "Notifications Email", en: "Email Notifications" },
  "notif.emailDesc": { fr: "Recevez des emails pour les événements importants", en: "Receive emails for important events" },
  "notif.push": { fr: "Notifications Push", en: "Push Notifications" },
  "notif.pushDesc": { fr: "Notifications dans l'application (bientôt disponible)", en: "In-app notifications (coming soon)" },
  "notif.sms": { fr: "Notifications SMS", en: "SMS Notifications" },
  "notif.smsDesc": { fr: "Recevez des SMS pour les événements urgents", en: "Receive SMS for urgent events" },
  "notif.quietHours": { fr: "Heures calmes", en: "Quiet Hours" },
  "notif.quietHoursDesc": { fr: "Suspendez les notifications pendant certaines heures", en: "Pause notifications during certain hours" },
  "notif.newMessage": { fr: "Nouveaux messages", en: "New messages" },
  "notif.newInquiry": { fr: "Nouvelles demandes", en: "New inquiries" },
  "notif.propertyViews": { fr: "Vues sur mes annonces", en: "Views on my listings" },
  "notif.recommendations": { fr: "Recommandations", en: "Recommendations" },
  "notif.marketing": { fr: "Actualités et promotions", en: "News and promotions" },
  "notif.weeklyDigest": { fr: "Résumé hebdomadaire", en: "Weekly digest" },
  "notif.urgentOnly": { fr: "Messages urgents uniquement", en: "Urgent messages only" },
  "notif.from": { fr: "De", en: "From" },
  "notif.to": { fr: "À", en: "To" },
  "notif.digestFrequency": { fr: "Fréquence du résumé", en: "Digest frequency" },
  "notif.daily": { fr: "Quotidien", en: "Daily" },
  "notif.weekly": { fr: "Hebdomadaire", en: "Weekly" },
  "notif.monthly": { fr: "Mensuel", en: "Monthly" },
  "notif.never": { fr: "Jamais", en: "Never" },
  "notif.comingSoon": { fr: "Bientôt disponible", en: "Coming soon" },
  
  // Errors
  "error.notFound": { fr: "Page introuvable", en: "Page not found" },
  "error.notFoundMessage": { fr: "La page que vous cherchez n'existe pas", en: "The page you're looking for doesn't exist" },
  "error.unauthorized": { fr: "Accès non autorisé", en: "Unauthorized access" },
  "error.generic": { fr: "Une erreur est survenue", en: "An error occurred" },
  "error.tryAgain": { fr: "Veuillez réessayer", en: "Please try again" },
  "error.connectionFailed": { fr: "Connexion échouée", en: "Connection failed" },
  
  // Toasts
  "toast.saved": { fr: "Enregistré", en: "Saved" },
  "toast.deleted": { fr: "Supprimé", en: "Deleted" },
  "toast.copied": { fr: "Copié !", en: "Copied!" },
  "toast.linkCopied": { fr: "Lien copié !", en: "Link copied!" },
  "toast.addedToFavorites": { fr: "Ajouté aux favoris", en: "Added to favorites" },
  "toast.removedFromFavorites": { fr: "Retiré des favoris", en: "Removed from favorites" },
  "toast.loginRequired": { fr: "Connexion requise", en: "Login required" },
  "toast.loginToFavorite": { fr: "Connectez-vous pour sauvegarder des favoris", en: "Login to save favorites" },
  "toast.profileUpdated": { fr: "Profil mis à jour avec succès !", en: "Profile updated successfully!" },
  "toast.descriptionGenerated": { fr: "Description générée avec succès !", en: "Description generated successfully!" },
  "toast.listingHidden": { fr: "Annonce masquée", en: "Listing hidden" },
  "toast.listingPublished": { fr: "Annonce publiée", en: "Listing published" },
  "toast.listingDeleted": { fr: "Annonce supprimée", en: "Listing deleted" },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "fr";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const translation = translations[key];
    if (!translation) {
      console.warn(`Missing translation for key: ${key}`);
      return key;
    }
    return translation[language];
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export default LanguageContext;
